#!/bin/bash

IP_REGEX="([0-9]+\.){3}([0-9]+)/[0-9]+"

# get the network interface
INTERFACES=(`ip a | grep -P $IP_REGEX | grep -oP "[^ ]+$"`)

# get the ips
IPS=(`ip a | grep -oP $IP_REGEX`)

# pair the interface and it's ip
n=${#INTERFACES[@]}
for (( i=0 ; i<$n ; i++ ));
do
	echo ${INTERFACES[$i]} ${IPS[$i]}
done
